### ISSUE TITLE
Data extraction for >48h?

### ISSUE THREAD

**Issue by gmeijers** [vingerha/gtfs2#102]
1. A clear and concise description of what the bug is.
Not trying to seem impatient, but I feel like data extraction shouldn't be taking this long. I selected https://gtfs.ovapi.nl/nl/ to download gtfs-nl.zip. The .zip file shows up in custom_components/gtfs2, and there's a .sqlite-file which is currently only 188kb in size.
  
2. Datasource(s).
https://gtfs.ovapi.nl/nl/archive/NL-20240816.gtfs.zip

**Release used**
- gtfs2 release: 0.4.8
- HA type: HAOS 2024.8.2

**Additional**
There are no errors in the log files. When I try to add the integration (e.g. add schedule on start/end stops), I get the message: (Still) extracting data, this will take time

HAOS log shows:
`Logger: custom_components.gtfs2.gtfs_helper`
`Source: custom_components/gtfs2/gtfs_helper.py:399`
`integration: GTFS 2 (General Transit Feed Specification) ([documentation](https://github.com/vingerha/gtfs2/wiki), [issues](https://github.com/vingerha/gtfs2/issues))`
`First occurred: 08:13:31 (8 occurrences)`
`Last logged: 11:20:20`
`Cannot use this datasource as still unpacking: ovapi240816`

The sqlite-file doesn't grow in size.

**Comment by mxbssn** [comment]
Having the same issue on my end. 
The sqlite file stay stuck at 188ko.

https://data.lemet.fr/documents/LEMET-gtfs.zip

**Comment by vingerha** [comment]
Put the integration in debug mode and re-add the datasource e.g. with a different name. Then add the logs, I cannot do anything without the logs

**Comment by gmeijers** [comment]
GTFS2 doesn't show up as an installed integration, so (as far as I know) it's not possible to put the integration in debug mode.

To check the status, I have to go to add integration and look for GTFS2.

**Comment by vingerha** [comment]
Put something like below in configuration.yaml and restart HA. then re-add the datasource and check logs
Is highly likely an issue with the pygtfs extracting part, datasource corrupt or not complying but as you hopefully undertsand, I cannot start testing each source

```
logger:
  default: warning
  logs:
    custom_components.gtfs2: debug

**Comment by vingerha** [comment]
Did you restart HA after updating the configyaml? The ewarning above is known but no issue. You should see multiuple rows that start with 'debug' like this
![image](https://github.com/user-attachments/assets/8d5b15aa-d051-4451-ab37-c116ffdc40bb)

**Comment by mxbssn** [comment]
I activated the debug logger on the integration, however despite it doesn't seem to be spitting out much more.

This error originated from a custom integration.

Logger: custom_components.gtfs2.gtfs_helper
Source: custom_components/gtfs2/gtfs_helper.py:399
integration: GTFS 2 (General Transit Feed Specification) (documentation, issues)
First occurred: 15:58:41 (4 occurrences)
Last logged: 15:58:41

Cannot use this datasource as still unpacking: gtfs

**Comment by gmeijers** [comment]
> Did you restart HA after updating the configyaml? The warning above is known but no issue. You should see multiuple rows that start with 'debug' like this ![image](https://private-user-images.githubusercontent.com/44190435/360450987-8d5b15aa-d051-4451-ab37-c116ffdc40bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzU3NDEsIm5iZiI6MTcyNDMzNTQ0MSwicGF0aCI6Ii80NDE5MDQzNS8zNjA0NTA5ODctOGQ1YjE1YWEtZDA1MS00NDUxLWFiMzctYzExNmZmZGM0MGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE0MDQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NWY3ZGVkNmUxM2U5ZDU2ZTFiZDYzMjM2YjhkYjRkYmE1NGFlNTFhNTA2MjlmMDAwYzZlYTZmYTUxM2JjZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U1YOsz61gL3-pd4GY9eszj0l1mQtJ8G1XnWEKFk49BI)

In which log should I find that? There are no such messages showing up in the core or supervisor log.

I'll try https://s3.gtfs.pro/files/uran/improved-gtfs-gtfs-nl.zip as data source now, but for the moment not a lot seems to be happening, very similar to the issue @mxbssn seems to be having.

**Comment by vingerha** [comment]
Well.. dozens of people that use this /... so pretty sure it is not the code (pretty sure <> 100%)
NL unpack takes about 1:15 depending on server specs

**Comment by mxbssn** [comment]
I've been having this issue for about a week now, not sure whether this was caused by HA's last update or not, anyway it simply doesn't work anymore.

**Comment by vingerha** [comment]
I am on Docker 2024.8.2 and yes.. I do see the blocking call error but that is not hindering the integration at all.
I will install HAOS later and check how to read logs, to be clear...not a HAOS fan

**Comment by vingerha** [comment]
> I've been having this issue for about a week now, not sure whether this was caused by HA's last update or not, anyway it simply doesn't work anymore.

nd when you say 'for about a week now' do you mean that you cannot extract since a week or that you have this blocking-call message. Do note that datasources (url) prove to be not stable over time (10+ examples I can recall)

**Comment by vingerha** [comment]
@gmeijers I have reinstalled a quick/dirty HAOS 2024 on my laptop and am extracting https://gtfs.ovapi.nl/nl/archive/NL-20240816.gtfs.zip for 15 mins now without any issue. The sqlite file is in Mb already. 
Hence I believe there is a different issue at your install but again...no logs = no idea

Core 2024.8.2
Supervisor 2024.08.0
Operating System 13.1
Frontend 20240809.0

**Comment by vingerha** [comment]
@gmeijers I used your link and this is what it got ot, no errors and as you can see about 1.5 hrs to extract on my Windows HyperV

![image](https://github.com/user-attachments/assets/ef16986f-c392-4098-a99f-ff93663f79ab)

I could setup some route with it too and logs are in 'Core'
![image](https://github.com/user-attachments/assets/4a8b3be9-552c-4a57-ab25-ab226cc1afa1)

**Comment by vingerha** [comment]
At present, I have no further input so no idea what might be wrong at your end.
