### ISSUE TITLE
[FEATURE]: Test that I've selected valid combo of direction, origin and destination stop

### ISSUE THREAD

**Issue by jpaulickcz** [vingerha/gtfs2#105]
First of all, thank you for this. I've been using original gtfs integration for about two years and it was fine for the three lines I have available from my apartment; but I've now wanted to put public transport times to additional HA instances I have at different places (my parents house etc.), and this has made it so much easier!

**Describe the solution you'd like**
<img width="660" alt="image" src="https://github.com/user-attachments/assets/78c6e568-a3a8-4faa-877a-835236e489f9">

I think it would be a good idea to have some sort of "test validity" button at this step in adding schedule. At least for my city, every line shows multiple stops of the same name - sometimes up to four (one entry for bus stop, one for tram stop, times two for each direction - and this is shown even when I've specifically selected a bus line; but it sometimes does use the tram terminal... it's just a mess :D).

Since I know my city's GTFS formatting and naming conventions for the stops a little by know, it was fairly easy to navigate, but I've still chosen the wrong combo a few times which resulted in the _"Start and/or End destination incorrect, possibly no transport 'today' or not in same direction, please check logs_" error message and having to start over, instead of just switching one stop and trying again.

Thanks for considering this :)

**Comment by vingerha** [comment]
Thanks for the feedback
On the rquirement, I believe you want to avoid re-re-re-re opening the same screen until you have a combination that works, not?
Actually... this is the next step after this screen, hence you recieve that message "...incorrect, possibly..."
There are some challenges and I am not very confident that this can be resolved easily.
0. this is part of configflow functionality of HA, it works but it is limited as well
1. when you are in that screen, it only has selected the data into the screen but your selection is not stored anywhere yet, like a webform and when in th emiddle of entering you refresh the screen, entries are gone
2. only after submit the entries become part of the configflow attributes
The only option I see is to 'submit', run the test and then go back to the screen if the test fails, I could prepopulate this then with the values just selected (i.e. those that failed).

Can you pleae confirm if I am assuming the correct things?

**Comment by jpaulickcz** [comment]
Yes, that is exactly correct. Once I get the message that the selected schedule is incorrect, I have to start over. If it would be possible to go back and re-fill all the selected values, that would of course worked as well :)

**Comment by vingerha** [comment]
And with this lightning speed of a solution, maybe you can help with the Czech translation, i.e provice the cz.json ?
No pressure if you donot want to :)
