### ISSUE TITLE
[Bug]: Realtime time format & delay data calculation 

### ISSUE THREAD

**Issue by mxbssn** [vingerha/gtfs2#112]
### Own Analysis

- [X] I cannot find my issue in the documentation

### A clear and concise description of what the bug is.

```shell
I have noticed that the time format for the Real time is different than the one given for the scheduled one, therefore the integration is unable to provide with the delay between the real-time and the scheduled one...   So the delay calculated always shows 0

Unable to add a screenshot, so here's the data :

Gtfs updated at
2 November 2024 at 12:08:55
Offset
0
Next departures lines
- departure: '12:16'
departure_realtime: '2024-11-02T11:16:45+00:00'
delay_realtime: 0
date: '2024-11-02'
stop_name: HOTEL DE VILLE
route: L1
route_long: '1'
headsign: Moulins Tournebride
trip_id: '1_62062590'
direction_id: 1
icon: mdi:bus
- departure: '12:31'
departure_realtime: '2024-11-02T11:29:46+00:00'
delay_realtime: 0
date: '2024-11-02'
```

### Provide details on the data source(s)

```shell
GTFS: https://data.lemet.fr/documents/LEMET-gtfs.zip

Realtime : https://proxy.transport.data.gouv.fr/resource/lemet-metz-gtfs-rt-trip-update
```

### Config in case of setup using location based departures

```shell
L1 LITALDU2 (local stop)
49,10016939409462
6,151061654090882
```

### Info on your installed version

0.5.2
HAOS

**Comment by vingerha** [comment]
This was already the case in 0.5.1 and earlier and tbh I am sure I had a reason for it but no longer sure which :)
From a HA basics perspective the UTC version is the one to use but when in cards, it is not always easy to display without lots of additional coding, so it is either BOTH times in UTC with TZ or both without.

**Comment by vingerha** [comment]
resolved with https://github.com/vingerha/gtfs2/releases/tag/0.5.3

Note: I also noticed that the delay (in seconds) is 0 for e.g. Palmbus (Cannes) even if there is an actual delay shown by the departure time. Not sure if I want to fix this :)

**Comment by mxbssn** [comment]
The same thing is happening is showing 0 anyway, whether the difference is + or -, unfortunately rendering the feature impractical

**Comment by vingerha** [comment]
The delay is NOT calculated, this comes straight from the provider, as I mentioned above.... you have to understand that this is a solution not just for one country and globally providers suck with their data, one can get: 'empy', null, 0, -  or a real number in seconds
And I am not very motivated in covering all forms of data issues.

**Comment by mxbssn** [comment]
Probably why all transport apps calculate the difference themselves.

**Comment by vingerha** [comment]
Likely but I do have an example out of the past where realtime was 1 minute earlier and delay in seconds was about 5 mins
... if I was going to the bus then I would have to assume an earlier start but likely get a 5 min delay

**Comment by vingerha** [comment]
So I decided to take the values as they come, the one thing I can do is to remove delay showing as 0 and make it '-'

**Comment by vingerha** [comment]
Actually, what I can do is if (!) there is no delay (empty/null/None/0) that I then try to use the time and calculate the delay

**Comment by mxbssn** [comment]
That'd be a clever solution, careful as there might be a loop there if there's no delay data shown with a 0, then it calculates 0 which triggers the whole thing again...

**Comment by vingerha** [comment]
Current idea is:
- add a new attribute, e.g. delay_deriv which will show the difference in schedule and realtime in seconds, it will show '-'  is not possible
- change the current delay to show '-' if it is 0

**Comment by mxbssn** [comment]
I have a suggestion; wouldn't it be better to show in mins? I don't know if that's easier/harder

**Comment by vingerha** [comment]
things is that I have a few examples here that show < 1 minute.... so what would that be then? 0 minute?
Could be min:sec ?

**Comment by mxbssn** [comment]
Yh I think streamlining the time format is best, so sticking to HH:MM:SS is good in my opinion :)
