### ISSUE TITLE
[FEATURE]: Periodic data refresh & automated processing

### ISSUE THREAD

**Issue by m1212e** [vingerha/gtfs2#116]
### Describe the solution you'd like

Hi, did you consider implementing automated refreshing of GTFS data after a certain amount?
Background is that some of my data sources only provide data for certain timeframes, often 1 month. The link to fetch the data from stays the same though. Would be awesome to have the extension auto refetch the data every x days to prevent running out of bus stop data and having to add the data manually each month.

**Comment by vingerha** [comment]
Can you please elaborate, what do you mean with amount?
Currently there is an option to re-load via automation at a pace you define yourselves.
https://github.com/vingerha/gtfs2/wiki/4.-Service-call

**Comment by m1212e** [comment]
Ah thats exactly what I need, just didn't expect it under "service call" and did not read the whole wiki page, thats on me. Thanks for the quick response!
