### ISSUE TITLE
[FEATURE]: Add pointers to GTFS  providers

### ISSUE THREAD

**Issue by creativethings** [vingerha/gtfs2#14]
**Describe the solution you'd like**
The most important step of the config is pointing to the GTFS provider. On the home page of the wiki pages you list the GTFS providers you tested, however, you do not list the providers. It would save prospect user of your integration a lot of time if you add a link to the providers you tested with.

**Describe alternatives you've considered**
Search the internet and hope I am using the right thing

**Additional context**
Many thanks for this project, it looks very promising and just what I need.

**Comment by vingerha** [comment]
Was outstanding, done
