### ISSUE TITLE
Next departure -1h

### ISSUE THREAD

**Issue by PetoMasaryk** [vingerha/gtfs2#16]
Next departures have value one hour ago.
Current time: 17:30
Next departure: 16:31

Steps/data to reproduce the behavior, e.g.
- url to the zip file :https://opendata.bratislava.sk/en/dataset/show/cestovny-poriadok-20240101
- route ID: 68993: 68 (None) - Dopravný podnik Bratislava, a.s.
- stop ID: 000000021000001 and 000000043700010
- outward

**Release used**
gtfs2 v0.3.3, HAOS as VM, 

Data refresh: 4 minutes
Offset: 0minutes
next_departures: 2024-01-17T16:31:00+00:00, 2024-01-17T16:38:00+00:00, 2024-01-17T16:46:00+00:00, 2024-01-17T16:54:00+00:00, 2024-01-17T17:09:00+00:00, 2024-01-17T17:24:00+00:00, 2024-01-17T17:39:00+00:00, 2024-01-17T17:55:00+00:00, 2024-01-17T18:11:00+00:00, 2024-01-17T18:26:00+00:00

**Comment by vingerha** [comment]
Thanks, I will have a look... from all the FTGS tested (see the referenc table), they are all in 'local' time, i.e. without Timezone...would be s surprise if Brat deviates. I personally would have liked the GTFS providers to provide UTC as a standard but...well... will check later this week

**Comment by vingerha** [comment]
I just noticed the copied "next_departures"....  and these are CORRECT ... HA demands that the times in attributes are shown in UTC... if you use these in card they will automatically show in your TZ

**Comment by vingerha** [comment]
closing as interpretation issue

**Comment by PetoMasaryk** [comment]
It is true, that if i use it in card, shown value is correct, however if i am calling next-departures via state_attr it shows the -1 hour value, so it is not very useful for example for assist etc.

**Comment by PetoMasaryk** [comment]
Mushroom template card as a basic output for "Next departure: {{ state_attr('sensor.markova_myto', 'next_departures').0 }}". 
I have also tried Entity card and it does show correctly Next Departure: in XY minutes.
And custom sentences for Assist. The not date-time format you have mentioned might be beneficial especially in Assist, because format 2024-01-18T10:03:00+00:00 is not working with TTS.

**Comment by vingerha** [comment]
jinja allows a lot to convert...try this
{{ (state_attr('sensor.markova_myto', 'next_departures').0 | as_datetime | as_local).time() }}

**Comment by PetoMasaryk** [comment]
thank you very much, it is working like a charm. Even TTS can respond with the departure
