### ISSUE TITLE
Kraków, Poland offers data in gtfs format, how do I add this?

### ISSUE THREAD

**Issue by spitfire** [vingerha/gtfs2#17]
Kraków, Poland [offers data in gtfs format](https://gtfs.ztp.krakow.pl/), how do I add this?
It seems the time tables for Buses and Trams are offered separately, so are the trip updates, service alerts and vehicle positions for each. I've tried adding [GTFS_KRK_A.zip](https://gtfs.ztp.krakow.pl/GTFS_KRK_A.zip) but nothing happens (all I can see in the logs is:
```
Loading GTFS data for <class 'pygtfs.gtfs_entities.Agency'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Stop'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Transfer'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Route'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Fare'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.FareRule'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.ShapePoint'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Service'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.ServiceException'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Trip'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Frequency'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.StopTime'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.FeedInfo'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Translation'>:
1 record read for <class 'pygtfs.gtfs_entities.Agency'>.
343 records read for <class 'pygtfs.gtfs_entities.Stop'>.
40 records read for <class 'pygtfs.gtfs_entities.Route'>.
5 records read for <class 'pygtfs.gtfs_entities.Service'>.
6 records read for <class 'pygtfs.gtfs_entities.ServiceException'>.
..14995 records read for <class 'pygtfs.gtfs_entities.Trip'>.
```

but when I try to set up a route or whatever after adding a data source it says: `(Still) extracting data, this will take time [(docu)](https://github.com/vingerha/gtfs2/wiki/1.-Initial-setup:-the-static-data-source#performance)`

**Comment by spitfire** [comment]
It is working for the [buses](https://gtfs.ztp.krakow.pl/GTFS_KRK_A.zip) but not for the [trams](https://gtfs.ztp.krakow.pl/GTFS_KRK_T.zip). They seem to both download and extract into my `/config/gtfs2/` folder:
```
du -hs /config/gtfs2/*
243.7M	/config/gtfs2/ZTP Kraków Autobusy.sqlite
8.0M	/config/gtfs2/ZTP Kraków Autobusy.zip
66.1M	/config/gtfs2/ZTP Kraków Tramwaje.sqlite
104.0K	/config/gtfs2/ZTP Kraków Tramwaje.sqlite-journal
2.9M	/config/gtfs2/ZTP Kraków Tramwaje.zip
``` 

Maybe it's some issue with today's file.

Is there any way to use the other files (one with service alerts and positions of trams/buses)?

**Comment by vingerha** [comment]
OK, can you point me to the tram file location? I assume you have two links, one for buses and one for trams. My intergation does not anticipate to have two in one zip :)

**Comment by spitfire** [comment]
and if you delete the filenames from the path you an see other files I mentioned as well listed. I've added them as separate sources, but while bus source works, tram does not. It might get fixed overnight :)

**Comment by locodwr** [comment]
Hi, I don't want to open another thread because it concerns the same data. I've been struggling with Krakow since yesterday. I managed to add buses and a stop nearby, but I can't figure out the real-time data. In the logs, I see errors:
2024-02-15 10:46:22.729 ERROR (MainThread) [custom_components.gtfs2.coordinator] Error getting gtfs realtime data, for origin: stop_1089_260809: Dworzec Główny Zachód (1) with error: Error parsing message
2024-02-15 10:55:33.592 ERROR (MainThread) [custom_components.gtfs2.coordinator] Error getting gtfs realtime data, for origin: stop_1089_260809: Dworzec Główny Zachód (1) with error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')).
@vingerha  Could you give me a hint? Perhaps it's an issue with the source data?

**Comment by vingerha** [comment]
On trams, the issue is with the feed_info.txt. The extraction library expects a date but this is not populated
your tram-zip (from url):
feed_publisher_name,feed_publisher_url,feed_lang,feed_start_date,feed_end_date,feed_version
"ZTP","http://ztp.krakow.pl/",pl,,,14.02.2024 01:03

example when working: 
feed_publisher_name,feed_publisher_url,feed_lang,feed_start_date,feed_end_date,feed_contact_email,feed_contact_url,feed_version
"RATP Dev",https://www.reseaumistral.com/,FR,20240131,20240331,,,"2024-01-31 15:09:39.613393 UTC"

On the bus-zip, this file is non existing and then the library apparently is OK with that. 
The only solution is to workaround as descibed in the doc... download the zip, remove the feed_info, place it in the gtfs2 folder and add it as a zip, not url (see doc)

**Comment by vingerha** [comment]
On realtime...please provide clear details, I cannot guess what you setup as stop

**Comment by locodwr** [comment]
The steps I took are: 
1. I set up a new route from the starting stop to the final one. 
![image](https://github.com/vingerha/gtfs2/assets/73441085/ae3b6d37-561b-4083-b215-103f63bf4bd9)
2. In the configuration, I set the URL for live data. 
![image](https://github.com/vingerha/gtfs2/assets/73441085/713f1f77-dc9d-4553-9c23-9ba311d6149f)
3. Then, I called the service. 
![image](https://github.com/vingerha/gtfs2/assets/73441085/4e7149d3-aa2f-4a14-bad5-d8d4e40f28f4)
4.  Next, I wanted to create a map with the bus positions, but unfortunately, I don't see the JSON files in the directory.

**Comment by vingerha** [comment]
Using that route without changing the stop, I get results
![image](https://github.com/vingerha/gtfs2/assets/44190435/f64fc604-a794-4b12-a39d-1104185b1cd3)

and the json is also generated (albeit it empty right now)... do read the doc

I am not checking alerts, 99% of the time there is nothing

**Comment by locodwr** [comment]
I have the same result for the route, but I don't have JSON files. Can you send a screenshot of how you called the service? Maybe I'm making a mistake here

**Comment by vingerha** [comment]
www/gtfs2 is the folder... my screen looks the same as yours and the file now contains data too

**Comment by locodwr** [comment]
Thank You!!! Even after reading the documentation multiple times, I missed 'www' in the path :(
We can consider my part of this issue closed

**Comment by spitfire** [comment]
I actually have some more questions about this:
1. Can I put two zips into a singe datasource somehow (trams and buses data is in separated zip files).
2. On the issue with data you spotted above: is there some workaround, or would I have to ask provider to correct data?

**Comment by spitfire** [comment]
> > inform provider and hope they that listen, else...sadly manual work remains involed ...but usually this is only once in a few months (with each zip update). I am also not sure why buses show a feed_info and trams donot

these zips seem to be updated more regularly, the buses were updated today, trams just 2 days ago.

**Comment by locodwr** [comment]
I haven't looked into the trams yet, but maybe we could work around it like this:
1. We create shell commands for:
   - downloading the tram data zip file,
   - unpacking the zip file,
   - removing unnecessary files,
   - compressing the prepared version.
   https://www.home-assistant.io/integrations/shell_command/
2. We create an automation that will trigger these commands.
3. Configuration of the integration to fetch the prepared file.

**Comment by vingerha** [comment]
Yeah...hmm...I have no good solution here. As per the doc...lots of providers deviate form standards (or: what I feel is a standard) and it is not very wanted to have fixes for each deviation. 
I will try to think of putting the service in place that auto-removes feed_info.txt....maybe this weekend

**Comment by vingerha** [comment]
I noticed your other message after finishing above one.... I already remove a 'pointless' file to reduce the size of the db and geeting this done was not too simple. If you have a soltuion to do this outside of the integration then that would be nice to know too. My above solution may (!??) look like adding an tockbox/option in the service to 'remove feed_info.txt'

**Comment by vingerha** [comment]
I have something ready but it needs some testing, will publish in the weekend as dev release

**Comment by spitfire** [comment]
I finally got back to it and tried setting up https://github.com/vingerha/gtfs2/wiki/5.-Visualizing-the-data this time. I have 2 routes (well basically 1, with 2 directions) and it shows up 2 json files, but they're usually empty.
```
┌─[root@a0d7b954-ssh] - [/config/www/gtfs2] - [2025-01-16 18:47:48]
└─[0] du -hs *
4.0K	ZTP Kraków Autobusy.rt
4.0K	route_126_0.json
4.0K	route_126_1.json
┌─[root@a0d7b954-ssh] - [/config/www/gtfs2] - [2025-01-16 18:47:51]
└─[0] cat *.json
{"features": [], "type": "FeatureCollection"}{"features": [], "type": "FeatureCollection"}#
```

When they do have something in them it's one location of a single bus, never too far from the starting point.

This is what I have configured in the route real-time data (it wouldn't let me past this dialog if I didn't put anything in the api key field).

<img width="407" alt="Image" src="https://github.com/user-attachments/assets/186edf76-f68b-41c5-95e3-f19318a5ef37" />

It seems to populate real time data:

```
arrival: 2025-01-16T18:29:00+00:00
day: today
first: false
last: false
offset: 0
agency_agency_id: agency_1
agency_agency_name: MPK S.A. w Krakowie
agency_agency_url: http://www.mpk.krakow.pl/
agency_agency_timezone: Europe/Warsaw
agency_agency_lang: pl
agency_agency_phone: +48 12 19 150
agency_agency_fare_url: None
agency_agency_email: None
origin_station_stop_id: stop_826_116702
origin_station_stop_code: None
origin_station_stop_name: Wieliczka Kopalnia Soli
origin_station_stop_desc: None
origin_station_stop_lat: 49.98456
origin_station_stop_lon: 20.055489
origin_station_zone_id: None
origin_station_stop_url: None
origin_station_location_type: 0
origin_station_parent_station: None
origin_station_stop_timezone: None
origin_station_wheelchair_boarding: None
origin_station_platform_code: None
origin_station_location_type_name: Station
origin_station_wheelchair_boarding_available: unknown
destination_station_stop_id: stop_51_7306
destination_station_stop_code: None
destination_station_stop_name: Politechnika
destination_station_stop_desc: None
destination_station_stop_lat: 50.071112
destination_station_stop_lon: 19.944663
destination_station_zone_id: None
destination_station_stop_url: None
destination_station_location_type: 0
destination_station_parent_station: None
destination_station_stop_timezone: None
destination_station_wheelchair_boarding: None
destination_station_platform_code: None
destination_station_location_type_name: Station
destination_station_wheelchair_boarding_available: unknown
route_route_id: route_126
route_agency_id: agency_1
route_route_short_name: 304
route_route_long_name: None
route_route_desc: None
route_route_type: 3
route_route_url: None
route_route_color: None
route_route_text_color: None
route_type_name: Bus
trip_route_id: route_126
trip_service_id: service_5
trip_trip_id: block_2110_trip_19_service_5
trip_trip_headsign: Dworzec Główny Zachód
trip_trip_short_name: None
trip_direction_id: 1
trip_block_id: block_2110
trip_shape_id: shape_3888
trip_wheelchair_accessible: None
trip_bikes_allowed: None
trip_bikes_allowed_state: unknown
trip_wheelchair_access_available: unknown
origin_stop_arrival_time: 2025-01-16T17:53:00+00:00
origin_stop_departure_time: 2025-01-16T17:53:00+00:00
origin_stop_drop_off_type: 0
origin_stop_pickup_type: 0
origin_stop_shape_dist_traveled: 1.85
origin_stop_sequence: 3
origin_stop_timepoint: 1
origin_stop_drop_off_type_state: Regular
origin_stop_pickup_type_state: Regular
origin_stop_timepoint_exact: true
origin_station_time_zone: null
destination_stop_arrival_time: 2025-01-16T18:29:00+00:00
destination_stop_departure_time: 2025-01-16T18:29:00+00:00
destination_stop_drop_off_type: 0
destination_stop_pickup_type: 0
destination_stop_shape_dist_traveled: 17.86
destination_stop_sequence: 17
destination_stop_timepoint: 1
destination_stop_drop_off_type_state: Regular
destination_stop_pickup_type_state: Regular
destination_stop_timepoint_exact: true
destination_station_time_zone: null
next_departures: 2025-01-16T17:53:00+00:00, 2025-01-16T18:04:00+00:00, 2025-01-16T18:14:00+00:00, 2025-01-16T18:24:00+00:00, 2025-01-16T18:44:00+00:00, 2025-01-16T19:04:00+00:00, 2025-01-16T19:24:00+00:00, 2025-01-16T19:43:00+00:00, 2025-01-16T19:58:00+00:00, 2025-01-16T20:18:00+00:00
next_departures_lines: 2025-01-16T17:53:00+00:00 (304), 2025-01-16T18:04:00+00:00 (304), 2025-01-16T18:14:00+00:00 (304), 2025-01-16T18:24:00+00:00 (304), 2025-01-16T18:44:00+00:00 (304), 2025-01-16T19:04:00+00:00 (304), 2025-01-16T19:24:00+00:00 (304), 2025-01-16T19:43:00+00:00 (304), 2025-01-16T19:58:00+00:00 (304), 2025-01-16T20:18:00+00:00 (304)
next_departures_headsign: 2025-01-16T17:53:00+00:00 (Dworzec Główny Zachód), 2025-01-16T18:04:00+00:00 (Dworzec Główny Zachód), 2025-01-16T18:14:00+00:00 (Dworzec Główny Zachód), 2025-01-16T18:24:00+00:00 (Dworzec Główny Zachód), 2025-01-16T18:44:00+00:00 (Dworzec Główny Zachód), 2025-01-16T19:04:00+00:00 (Dworzec Główny Zachód), 2025-01-16T19:24:00+00:00 (Dworzec Główny Zachód), 2025-01-16T19:43:00+00:00 (Dworzec Główny Zachód), 2025-01-16T19:58:00+00:00 (Dworzec Główny Zachód), 2025-01-16T20:18:00+00:00 (Dworzec Główny Zachód)
gtfs_updated_at: 2025-01-16T17:50:06.244954+00:00
origin_stop_alert: no info
destination_stop_alert: no info
gtfs_rt_updated_at: 2025-01-16T17:51:06.496048+00:00
next_departure_realtime: 2025-01-16T17:54:37+00:00
next_departures_realtime: 2025-01-16T17:54:37+00:00
attribution: MPK S.A. w Krakowie
device_class: timestamp
icon: mdi:bus
friendly_name: 304 - Wieliczka (Kopalnia Soli)->Kraków (Politechnika)
```

but the geolocation json files are rarely being populated, any idea why?

**Comment by vingerha** [comment]
I cannot comment on quality of data from all providers. The fact that it updates 'sometimes' means that at-least you get data  so highly likely not a a tech issue.
For my 2 local providers, one is quite good, i.e. I receive many bis-location-updates and tbh ... I do not follow their buses to see if they report the correct lat/lon :)...  For the other, only <5% of the cases I receive something, not clue what/why/when and the provider does not respond. 
Then I have a Dutch provider for my kid and they have nothing (seemingly) real-time in Amsterdam (of all places)
