### ISSUE TITLE
This is working for Dublin Bus

### ISSUE THREAD

**Issue by davefrooney** [vingerha/gtfs2#18]
Thanks for the work on this project. The Dublin Bus info is working with this integration

The URL to the zip is [https://www.transportforireland.ie/transitData/Data/GTFS_Dublin_Bus.zip](https://www.transportforireland.ie/transitData/Data/GTFS_Dublin_Bus.zip)

**Comment by vingerha** [comment]
Could you maybe let me know if you tried the Realtime too? I noticed there is some dev access to it

**Comment by davefrooney** [comment]
I have added in my API key but it tells me there is no realtime information. Could it take some time to load?

![image](https://github.com/vingerha/gtfs2/assets/2380666/a5381715-c850-4df2-ad56-a7ba7b44a722)

**Comment by vingerha** [comment]
it should show a field gtfs_rt_updated if you added the proper URL to the realtime field (config)

**Comment by davefrooney** [comment]
I am getting the following error in HA

`Error getting gtfs realtime data, for origin: 8220DB004495: Hawkins Street (1) with error: Error parsing message
`

I'm using the URL from the API site

[[](`[](https://developer.nationaltransport.ie/api-details#api=gtfsr&operation=TripUpdates)`)](https://developer.nationaltransport.ie/api-details#api=gtfsr&operation=TripUpdates)

The URL mentioned is

[[https://api.nationaltransport.ie/gtfsr/v2/TripUpdates](url)](https://api.nationaltransport.ie/gtfsr/v2/TripUpdates)

There is an area to test the API in the backend and the data is provided. Could it be an issue with the format? Here's a sample

`HTTP/1.1 200 OK

content-length: 5155323
content-type: application/json
vary: Origin

{
    "header": {
        "gtfs_realtime_version": "2.0",
        "incrementality": "FULL_DATASET",
        "timestamp": "1708344862"
    },
    "entity": [{
            "id": "T1",
            "trip_update": {
                "trip": {
                    "trip_id": "3873_65962",
                    "start_time": "07:15:00",
                    "start_date": "20240219",
                    "schedule_relationship": "SCHEDULED",
                    "route_id": "3873_61442",
                    "direction_id": 0
                },
                "stop_time_update": [{
                        "stop_sequence": 31,
                        "arrival": {
                            "delay": -1
                        },
                        "departure": {
                            "delay": -1
                        },
                        "stop_id": "8470B3507101",
                        "schedule_relationship": "SCHEDULED"
                    },
                    {
                        "stop_sequence": 32,
                        "arrival": {
                            "delay": 1526
                        },
                        "departure": {
                            "delay": 1526
                        },
                        "stop_id": "8470B521231",
                        "schedule_relationship": "SCHEDULED"
                    },
                    {
                        "stop_sequence": 33,
                        "arrival": {
                            "delay": 1534
                        },
                        "departure": {
                            "delay": 1534
                        },
                        "stop_id": "8470B530311",
                        "schedule_relationship": "SCHEDULED"
                    }
                ],
                "vehicle": {
                    "id": "1473"
                },
                "timestamp": "1708344862"
            }
        },`

**Comment by vingerha** [comment]
Yeah...it should kick back protobuf...that is what my integration uses
here is an example of the format https://proxy.transport.data.gouv.fr/resource/palmbus-cannes-gtfs-rt-trip-update
Yours is the 3rd type/format I see, Bay of SanFrancisco uses yet another one
Thing is, I cannot build for exceptions, too much effort to maintain

**Comment by davefrooney** [comment]
The realtime seems to be working now with the latest release. The X-api key needs to be set to header. The URL for the data should be changed to https://www.transportforireland.ie/transitData/Data/GTFS_Realtime.zip
