### ISSUE TITLE
[FEATURE]: Don't assume 'None' for agency_id when column is missing from route table

### ISSUE THREAD

**Issue by CityDweller** [vingerha/gtfs2#19]
I see this entry in my log and it is causing me to miss other issues that may be present:

2024-02-19 18:28:55.982 WARNING (MainThread) [custom_components.gtfs2.sensor] Agency ID 'None' was not found in agency table, you may want to update the routes database table to fix this missing reference

In my case, the agency.txt file has "CATS" as the agency_id value  and it is the only entry in the file.  The routes.txt file doesn't have a column for agency_id--and I don't believe it is required when there is only a single agency represented--my opinion only.

Can this message be scaled back to maybe only written upon start up of the service?

**Comment by vingerha** [comment]
The agency is used to select the timezone it belongs to and can indeed be missing/incorrect.... I cannot tell as the loading of that is done by the external pygtfs library (out of my control). At the moment it indeed runs every time the sensor collects data and I have no 1-time-only setting for that. What I can do is to change the log level to 'debug'.

**Comment by CityDweller** [comment]
The agency table is present, it is just the agency_id value doesn't match what is assumed from the routes table what that table doesn't have an agency_id colunn.

If 'debug' can keep the message from showing up twice a minute, that would be great.

**Comment by vingerha** [comment]
Changed it but will await more changes before creating a new release. If you are in a hurry you can update sensor.py yourselves :)

**Comment by vingerha** [comment]
Fixed in 035
