### ISSUE TITLE
[FEATURE]: use now().tzinfo in place of UTC

### ISSUE THREAD

**Issue by danito** [vingerha/gtfs2#2]
Hi,
in my gtfs routes.agency_id is Null and agency.timezone is also Null, so returned time for departure_time is in UTC :
https://github.com/vingerha/gtfs2/blob/cc1a262119e9f5a471f015723ebc582b9885890a/custom_components/gtfs2/sensor.py#L197
Can we have an option to use now().tzinfo if gtfs timezone is missing so that the sensor returns local time?
Workaround is of course to create a new template sensor.

Thanks

**Comment by vingerha** [comment]
What I will implement is this
1. agency TZ (as this is related to the data and not what you put in the HA instance)
2. if no agency TZ: HA instance TZ
3. if no HA instance TZ defined: UTC

**Comment by vingerha** [comment]
added with 0.1.5
