### ISSUE TITLE
This screen about intercity trains is confusing and unclear

### ISSUE THREAD

**Issue by DeflateAwning** [vingerha/gtfs2#25]
**Problem:**

I don't understand what this screen is asking:
![image](https://github.com/vingerha/gtfs2/assets/11021263/2c4d4846-fa76-4cdb-baba-220f97c7117f)

There are no inter-city trains in my city. Which options am I supposed to pick? 

If you can explain what's going on here, maybe I can suggest some better wording?

**Comment by vingerha** [comment]
I see the issue...is a bit odd. 
This screen allows to selectr between using 
- Trains, which have a start/end using cities (manually entered) 
- Non-trains, selecting from start/end stops provided by the data

**Comment by vingerha** [comment]
Suggestion... and do note that clicking on the 'doc' link will provide more details...it is impossible to provide all explanations in (size-limited) config screens
![image](https://github.com/vingerha/gtfs2/assets/44190435/359a4b57-22a3-4f4d-bcef-70a798b7af6e)

**Comment by DeflateAwning** [comment]
You shouldn't have to visit documentation to understand what the options are.

I still don't understand, even after [reading the docs](https://github.com/vingerha/gtfs2/wiki/2.-Setup-a-new-route).

What happens when you click each button? Which button did you click in your bus example in the documentation?

**Comment by vingerha** [comment]
You are the first and only that seems to have an issue with this, so if you think you can do better...please suggest a PR

**Comment by DeflateAwning** [comment]
I'm still trying to understand what the buttons do so that I can.  Can you please try explaining what happens when you choose each option? 

Sorry I'm not understanding. Please don't get angry, though.

**Comment by vingerha** [comment]
First : allows to select transport of those provided through the zip...but it excludes (!) selecting trains
Second: allows to setup train connections, based on (manually) entered cities
WHY? because train stations often have a lot (!) of stop_id and you'd need to configure each one of them for both start and end

**Comment by vingerha** [comment]
Hey, are you OK with the above ? I alreayd brought a few things to production but I am not totally happy myself as well... 100% will never be achieved but maybe you have the right response to my blind eye(s) ?
Else, please close the topic...if no response I will close in a few days myself

**Comment by DeflateAwning** [comment]
Ah sorry, thanks for the explanation. 

May I propose this as the text?

> Select a type of transport:
> 1. **Intracity Transport:** exclude selecting intercity trains
> 2. **Intercity Transport:** configure cities and stop IDs manually

Let me know if I'm still missing the point though.

**Comment by vingerha** [comment]
But that is not the situation
1. can have long distance buses, can be for a region, country, etc.
2.  is ONLY trains and even trains have intra-city stops

**Comment by DeflateAwning** [comment]
I'll try again:

> Select a display option:
> 1. **Default:** Datasource includes many types of transit.
> 2. Datasource is too large to enumerate; configure cities and stop IDs manually

**Comment by DeflateAwning** [comment]
Can you give an example of a city/GTFS source that I can view to better understand these two options?

**Comment by vingerha** [comment]
Thx for sticking / persevering :) but again....this is not what it is
1. covers all transport, except trains
2. covers only trains
Netherlands ...there is only one zip covering the whole country, same for Switzerland
Germany has various offerings, one for country/all, one for longdistance trains and multiple for regional trains

**Comment by vingerha** [comment]
I am closing this topic as it seems to not find a solution and no-one else joins or comments.

**Comment by DeflateAwning** [comment]
Hold on, your solution is to keep it as-is? I'm convinced that any of the options above are better than what's currently there.

**Comment by vingerha** [comment]
I changed it a bit in the latest release but you should also understand that I cannot uphold a discussion that has seemingly no interest to the larger group of users

**Comment by vingerha** [comment]
And donot get mer wrong...if you have a matching good proposel...happy to implement, I donot have the single view on the truth :)

**Comment by vingerha** [comment]
New setup
![image](https://github.com/vingerha/gtfs2/assets/44190435/95bb6a3f-1bcc-48c4-a108-e97399d0ae7e)

**Comment by DeflateAwning** [comment]
This looks great, way better, thanks!
