### ISSUE TITLE
[FEATURE]: Automatically re-download the GTFS zip file periodically

### ISSUE THREAD

**Issue by DeflateAwning** [vingerha/gtfs2#27]
**Describe the solution you'd like**
I want the GTFS zip file to update automatically.

I'm not certain if it does this currently or not. If it does, can you add an indication that it does to the actual screens in HASS?

**Describe alternatives you've considered**
I think currently you have to manually trigger the update?

The [relevant place in the docs](https://github.com/vingerha/gtfs2/wiki/1.-Initial-setup:-the-static-data-source) doesn't mention whether it is automatically updated or not.

**Comment by vingerha** [comment]
Read the docs....use the service call

**Comment by vingerha** [comment]
Closing as already covered in doc 
https://github.com/vingerha/gtfs2
https://github.com/vingerha/gtfs2/wiki
https://github.com/vingerha/gtfs2/wiki/4.-Service-call
