### ISSUE TITLE
[FEATURE]: Add Zagreb (ZET) as working datasource

### ISSUE THREAD

**Issue by BeardedTinker** [vingerha/gtfs2#28]
Just finished recording video on this wonderful integration and want to verify that Zagreb (ZET) GTFS static data is working for Trams and Busses. 
The link to GTFS data source is here:
https://www.zet.hr/odredbe/datoteke-u-gtfs-formatu/669

On that page there is test link for live data, but I'm not sure if it's working or how to verify that.

Plus link to static data that works.

Thank you for AWESOME integration!

**Comment by vingerha** [comment]
Many thanks, esp. when coming from someone that helped me (!) with my first paces in HA :)
