### ISSUE TITLE
New Working Provider

### ISSUE THREAD

**Issue by markjhealey** [vingerha/gtfs2#32]
Uncertain how to add this, so raised as an issue.

Provider: East Yorkshire Buses
Geo-covering: Region
Type: B
Static: x
Link: https://www.eastyorkshirebuses.co.uk/open-data
extract: 0.25

The downloaded zip file is just under 4Mb.
This extracts to a 46.5Mb sqlite database.

**Comment by vingerha** [comment]
THANKS
