### ISSUE TITLE
Setup error: Unknown error occurred,  list index out of range

### ISSUE THREAD

**Issue by FabienD74** [vingerha/gtfs2#35]
**Describe the bug**
Hello, 
I installed the datasource ( took some time 5-10 minutes...). 
Then "Setup a new route":
- i selected the datasource ( named "Tec" in my case)
- then option "0:all"
- then "All excluding trains"  ( tec is a bus company :-)  )
- i search "116"  , the right line appears in the selection ("B0116-20881: 116 (Soignies - Br.-le-Comte - Rebecq -Tubize - Halle) - TEC Brabant Wallon"). 
- I let 'Outboud' bt defautt
- click on 'Submit"

-> I receive a red message on top "Unknown error occurred" 

Setup failed.
I can't go any furter.

Regards
Fabien 

Steps/data to reproduce the behavior, e.g.
- url to the zip file  https://data.gtfs.be/tec/gtfs/be-tec-gtfs.zip
- route ID  = i'm not yet there
- stop ID   : i'm not yet there
- outward/return : both are failing

**Release used**
Which gtfs2 release and HA type (HAOS/Container)        => HAOS

**Additional**
Please add logs if helpfull

  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 405, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 502, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gtfs2/config_flow.py", line 260, in async_step_route
    return await self.async_step_stops()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gtfs2/config_flow.py", line 271, in async_step_stops
    last_stop = stops[-1:][0]
                ~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by vingerha** [comment]
The error occured as it finds no trips for the route... which is an issue with your data provider
It is even more odd as there are 209.605 trips in the file, but they are all for route_id N2720-21224 (Namur - Bovesse)
So my guess is that the provider messed up somewhere so try contacting them or find another (good?) source...if existing, I am closing this ticket as I cannot do anything for you here.

**Comment by vingerha** [comment]
This one looks better....
https://data.gov.be/en/dataset/tec

**Comment by vingerha** [comment]
and btw.... my table with 'tested' connections even show another one which seemed to work too
Chekc here
https://github.com/vingerha/gtfs2/wiki
