### ISSUE TITLE
The link to the dutch gtfs is working, but the data inside is not. When i try to load the data in the integration, it' almost instand done and i can't use the integration with this data. Maybe i'm doing it wrong, if so can you help me or explain to me what file i have to link or what url i have to past in the integration to have it working propperly? Thanks in advance.

### ISSUE THREAD

**Issue by Sarnog** [vingerha/gtfs2#37]
**Describe the bug**

Steps/data to reproduce the behavior, e.g.
- url to the zip file
- route ID
- stop ID
- outward/return

**Release used**
Which gtfs2 release and HA type (HAOS/Container)

**Additional**
Please add logs if helpfull

**Comment by vingerha** [comment]
tbh, no clue what you did via the way you descibe it..... please let me know step by step what you did and where it stops working
Do note the unpacking takes 2-3 hours, see the table here https://github.com/vingerha/gtfs2/wiki

**Comment by Sarnog** [comment]
I installed the intergration via hacs. After the reboot of home assistant i went to the integrations and started the setup of the integration.

First i clicked "setup a new data source".
Via the link in your "docu" i went to the Dutch website: https://gtfs.ovapi.nl/nl/

I selelected URL, pasted the url in the zip location, gave it a name and click send.

This didn't work, as soon as i went back to the integration and clicked on "create schedule on start/end stops", i get an error: "Data collection issue: ZIP file not existing in the correct folder, note that it is capital-sensitive"

I also tried to link to the specific files in the link (i tried all of them), but i always get the same error.

**Comment by vingerha** [comment]
https://gtfs.ovapi.nl/nl/ is not the link to the zip file, it is a link to multiple sources for gtfs, use it in a browser and you will find out which file to choose, i.e. .... gtfs.ovapi.nl/nl/gtfs-nl.zip.
The table does not contain direct links as there are many other like realtime/vehicle/alerts and I chose to not post indiv. url

**Comment by Sarnog** [comment]
I installed the intergration via hacs. After the reboot of home assistant i went to the integrations and started the setup of the integration.

First i clicked "setup a new data source".
Via the link in your "docu" i went to the Dutch website: https://gtfs.ovapi.nl/nl/

I selelected URL, pasted the url in the zip location, gave it a name and click send.

This didn't work, as soon as i went back to the integration and clicked on "create schedule on start/end stops", i get an error: "Data collection issue: ZIP file not existing in the correct folder, note that it is capital-sensitive"

I also tried to link to the specific files in the link (i tried all of them), but i always get the same error.

**Comment by Sarnog** [comment]
> https://gtfs.ovapi.nl/nl/ is not the link to the zip file, it is a link to multiple sources for gtfs, use it in a browser and you will find out which file to choose, i.e. .... gtfs.ovapi.nl/nl/gtfs-nl.zip.
> The table does not contain direct links as there are many other like realtime/vehicle/alerts and I chose to not post indiv. url

So if i understand you correctly, the gtfs.ovapi.nl/nl/gtfs-nl.zip file is not working eighter out of the box? I tried it and it gave me the same result as i described above.
Is there any way to make it work? And if so, do you know where i can find some documentation about how to fix it? I understand you don't want to dive in it, but maybe you know some good existing info about it? Thanks again.

**Comment by vingerha** [comment]
I have no clue how you came to this conclusion, I told you that the link you sent was not pointing to the zip and I assumed you to use a url-format ... so do use  :)
https://gtfs.ovapi.nl/nl/gtfs-nl.zip

**Comment by Sarnog** [comment]
> I have no clue how you came to this conclusion, I told you that the link you sent was not pointing to the zip and I assumed you to use a url-format ... so do use  :)
> https://gtfs.ovapi.nl/nl/gtfs-nl.zip

Sorry English is not primary language, so i misunderstand. Thanks for the explaination, the integration is installing the data now. Thanks again!
