### ISSUE TITLE
Geographic stops not giving the right sens /hours

### ISSUE THREAD

**Issue by hal01** [vingerha/gtfs2#38]
Hello 
(following my post on hacf forum)

I have an issue with next departure around a localisation.

When I'm creating around my place.
I have 4 stops created 

- two corresponding to the location close to my place with the 2 sens (HLO001 and HLO002)
- one for the stop in sens 2 for the stop before my place (FAY002)
- on for the stop in sens 1 before my place (PIM001)

Stops HLO001 is my concern, because not giving the hours of bus on the good place 

HLO001 & HLO002 corresponding to the 2 sens of the stop id 1148  which is Hautes loges (in Stops.txt)

This is for Ilevia network in Lille
- url :  (https://opendata.lillemetropole.fr/api/v2/catalog/datasets/transport_arret_transpole-point/alternative_exports/gtfszip)
- location used (50.6685652680685, 3.087443162094925)

HLO002 entity is having the GOOD hours and sens 
`Gtfs updated at
12 mars 2024 à 18:55:02
Device tracker ID
zone.home
Next departures lines
- departure: '18:58:00'
stop_name: Hautes Loges
route: '50'
route_long: MARCQ COLLÈGE <> GRAND SAINT ANDRÉ
headsign: Marcq En Baroeul Ferme Aux Oies
trip_id: '4954142'
icon: mdi:bus
- departure: '19:09:00'
stop_name: Hautes Loges
route: L5
route_long: MARCQ / LA MADELEINE<>HAUBOURDIN LE PARC
headsign: Marcq En Baroeul Ferme Aux Oies
trip_id: '4960832'
icon: mdi:bus
`

**When HLO001 is having the hours of FAY002**

`Gtfs updated at
12 mars 2024 à 18:49:02
Device tracker ID
zone.home
Next departures lines
- departure: '19:01:00'
stop_name: La Fayette
route: '50'
route_long: MARCQ COLLÈGE <> GRAND SAINT ANDRÉ
headsign: Saint Andre Grand St Andre
trip_id: '4954251'
icon: mdi:bus
- departure: '19:23:00'
stop_name: La Fayette
route: '50'
route_long: MARCQ COLLÈGE <> GRAND SAINT ANDRÉ
headsign: Saint Andre Grand St Andre
trip_id: '4954143'
icon: mdi:bus
- departure: '19:25:00'
stop_name: La Fayette`

**Release used**
latests released

**Additional**
Remark : even by changeing the reference location, I'm not able to create a FAY001 stop ... don't undertand why ...
even if the location is in Stops.txt file 
I check GPS coordinate of FAY001 is Ok in stops.txt file (50.67153,3.089428)

When using the route to define a route starting HLO001 to the final stop of th line I have good information.

It's really when using geographique creation of the stops entity

**Comment by vingerha** [comment]
I will have a look but analysis is a lot of work and usually very disappointing ...in 90%+ of the cases it is data related which is not where I want to spend my time with

**Comment by vingerha** [comment]
After analysing my own stops...noticed they were wrong too. 
I have a new release, 0.4.0, please check and see if this resolves yours (it does for me)

**Comment by hal01** [comment]
YES Bravo

It worked for me too.

That's now giving the good stop name and hours for geaographic point.
