### ISSUE TITLE
[FEATURE]: creating stops hours by selection in stops list (in addition of localisation around mode)

### ISSUE THREAD

**Issue by hal01** [vingerha/gtfs2#39]
I would like to have hours on a stop, (without creating a route) by selecting a stop in a list or entering it's code.

WOuld be perfect to create sort of timetable on a stop in a fixed area.
Thanks

**Comment by hal01** [comment]
Could be by creating a sensor through edition of a file , or something like that...

**Comment by vingerha** [comment]
This is already possible if you create a zone on the stop itself, then setup the zone/person thing and reduce the radius after it is setup....do try, works for me.
This of course only works if the the data-provider has the correct location for the stop supplied :)
