### ISSUE TITLE
[FEATURE]: Increase max range in "CONF_RADIUS"

### ISSUE THREAD

**Issue by cvc90** [vingerha/gtfs2#46]
Hi @vingerha, 

Currently the variable "CONF_RADIUS" is set with min=50, max=500, I think that for cities it is correct but for small towns or remote houses I think it should be possible to increase the range to 1500M or even more.

How about increasing the max range of this variable in the config_flow.py file? Thank you.

**Comment by vingerha** [comment]
I myself live in a small town and just took 'something' that applied to me. When in a city 500m already could explode the response and slow it down (dead) esp. if you have additional real-time setup. Alternatives are to create other 'areas' and use that but the reporting in HA becomes mre complex too. Hence, will extend it to 2km (??) and add a warning ...would that help?

**Comment by cvc90** [comment]
I think it could be useful in many cases to be able to increase the rank, I understand what you say that it could saturate "HA", but with a warning would be good for people to be warned of the consequences of setting a high rank, the vast majority of users will not touch the default rank setting.

**Comment by vingerha** [comment]
I am a bit concerned because of the risk. If you raise it too high it could kill HA and a reboot will not help as it would start again, requiring diving into the .storage folder with even more risks. I need to think this through, possibly do a initial 'call' to check #stops...

**Comment by cvc90** [comment]
Regular people with the range at 400M (default) like this currently will not have problems, by increasing the maximum range since it will not modify their current range.

People who increase the range between 500M and 1500M may have problems if they are using it in an inappropriate place such as in the city, it would be due to poor user configuration, in this case we can limit it to only 1 stop, so as not to saturate it.

People who increase the range between 500M and 1500M and use it in cases like the one I mentioned should not have any type of problem.

**Comment by vingerha** [comment]
In other words...you know as well as I that people do not read the risks/conditions (myself included) and the damage is too high if they skip understanding their choice

**Comment by vingerha** [comment]
Just for my thoughts and yours.. I may be able limit it to the top 15 stops closest to the location/zone/person

**Comment by vingerha** [comment]
Resolved with 0.4.4. Max radiis is now 5000 but a hard limit if this surpasses 15 stops

**Comment by cvc90** [comment]
Thanks for the improvement 😄
