### ISSUE TITLE
[FEATURE]: Add option to set Accept: application/x-protobuf header

### ISSUE THREAD

**Issue by pcuser42** [vingerha/gtfs2#49]
**Describe the solution you'd like**
Auckland Transport's realtime API returns JSON data by default, but does return Protobuf if the `Accept` header is set to `application/x-protobuf`. Add an option to set this header if required by the data source.

**Describe alternatives you've considered**
Looking at Auckland Transport's documentation, this header is the only way to get Protobuf data, and getting realtime data without it is not possible. I've tried adding a .pb extension to the URL in case this somehow worked, but just resulted in a 404.

**Additional context**
Static GTFS data source: https://gtfs.at.govt.nz/gtfs.zip

Realtime API data requires an API key. The URLs I've been using (with the key in the header):
https://api.at.govt.nz/realtime/legacy/tripupdates
https://api.at.govt.nz/realtime/legacy/vehiclelocations
https://api.at.govt.nz/realtime/legacy/servicealerts

**Comment by vingerha** [comment]
try 0.4.4.1, as I donot have local/static data I only tested with the service call and that collects the correct format

**Comment by vingerha** [comment]
Too many things to work on and only limited testing ... typo fixed  in 0.4.4.2

**Comment by pcuser42** [comment]
Thanks @vingerha, no more errors and debug data suggests the API can now be contacted. 😄 

I'm just getting a dash in the realtime attributes, but it's also possible that I've misconfigured something else, so will keep digging on this.

**Comment by vingerha** [comment]
Do try the service call so you can see the readable data too

On 8 Apr 2024, at 09:33, Alex Burgess ***@***.***> wrote:

﻿

Thanks @vingerha<https://github.com/vingerha>, no more errors and debug data suggests the API can now be contacted. 😄

I'm just getting a dash in the realtime attributes, but it's also possible that I've misconfigured something else, so will keep digging on this.
