### ISSUE TITLE
[BUG] Updating Dataset by a local zip File throws out an Unknown Error

### ISSUE THREAD

**Issue by dafunkydan** [vingerha/gtfs2#56]
**Describe the bug**
When Updating Dataset by a local zip File (not by URL) via Service-Call, an Unknown Error occures.

**Describe the Solution**
Even if updating by zip File, the Field "URL" needs to contain something. Even google.com works, then the zip gets extracted.

**Release used**
gtfs2: 0.4.4.7
HA: HAOS
Core: 2024.4.3

**Comment by dafunkydan** [comment]
Solution, see in the Inital Post.
I just stumbled across this, and wanted to track this for future references.

**Comment by vingerha** [comment]
![image](https://github.com/vingerha/gtfs2/assets/44190435/90909829-54bd-4b15-b8f7-5e21c1d06255)
