### ISSUE TITLE
adding new stop

### ISSUE THREAD

**Issue by Meggs31** [vingerha/gtfs2#59]
When trying to add a new stop in a crowded area there is a new warning that there are more than 15 stops in the vicinity and i should decrease the radius. I think the option is only afterwards available but the stop isn't created. 

I am using version 0.4.5 on HA

**Comment by vingerha** [comment]
Small 'fix' ..... it will now allow you to set it up but for the configuration after it will complain. Main reason is risk on system performance...which I cannot measure so no clue if 15 is a limit (just took 'something') esp. when realtime is added this may become a showstopper.
Try 0.4.5.1
