### ISSUE TITLE
Sensor going unknown regularly

### ISSUE THREAD

**Issue by TwitchingAstronaut** [vingerha/gtfs2#60]
**Describe the bug**
sensor for train route goes "unknown" from midnight (AEST) +-1hr until 10:00am +- 5min

![image](https://github.com/vingerha/gtfs2/assets/91707474/2c9be802-fbad-4a0a-a9fc-74bf20f0a352)

Steps/data to reproduce the behavior, e.g.
- url to the zip file: https://gtfsrt.api.translink.com.au/GTFS/SEQ_GTFS.zip
- route ID: CLSH-3582
- stop ID: 600264
- outward/return: Inbound

**Release used**
Which gtfs2 release and HA type (HAOS/Container)
HA version: Core 2024.4.3 (docker)
GTFS2 version: 0.4.5

**Additional**
Please add logs if helpfull

**Comment by dafunkydan** [comment]
Without having trying to reproduce: Maybe there is just no Connection during that Timespan?
I had a similar observation, til i found out that during the Nighttime, although in Real-Life it is (looks like) the same Connection, internally it is a different Route.
So your "Daytime" Route renders unavailable, while another Route "Nighttime" becomes available.
Just guessing, but maybe you didn't check for that?

**Comment by vingerha** [comment]
> sensor for train route goes "unknown" from midnight (AEST) +-1hr until 10:00am +- 5min

Does it automatically ocme back?

**Comment by dafunkydan** [comment]
Have you confirmed between 04.30am and 10.00am it is 

> route ID: CLSH-3582

The linked Timetable shows a Connection on a Route. I couldnt see the Route ID.

Like i said: I have a Tramline: Same Name, same Start, same Stop, same Stops in between. Guess what: Three different Route IDs. Sometimes its just a minor change (e.g. Platform change, whatever) that may make the Transportation Service give it another Route ID. Or even not that. As almost all Customer never notice, they are sometimes quite creative 😆

**Comment by vingerha** [comment]
If there is no further feedback then kindly close it or I will close it in the next 1-2 days

**Comment by TwitchingAstronaut** [comment]
not resolved, but nothing further to add

**Comment by vingerha** [comment]
There are multiple questions unanswered hence. Your expectation is based on timetable logic but you forget that HA itself also has influence on the state which I cannot control. From my pov, the sensor should be unknown if there is no data/content, not because of the time-of-day.

**Comment by dafunkydan** [comment]
@TwitchingAstronaut Have you checked for:
- Your Stop ID, if there is another Connection ID serving your desired Route during the Night?
- Other Stop IDs close nearby, that might serve your desired Connection?

It is quite likely that a Connection from A to B runs during the Day the as ConnectionID 111 from StationID 88888, and in the Night as ConnectionID 112 from StationID 88889.
