### ISSUE TITLE
Issues adding source files.

### ISSUE THREAD

**Issue by Sheepish2** [vingerha/gtfs2#64]
**Describe the bug**
Unable to attach logs as there isn't any to add. However I've installed GTFS through manual install (Couldn't find on HACS) and then placed my zip into the folder and its been about 3 days and no SQLITE.journal file has been created. the google_transit.zip is just switching to google_transit_temp.zip and not doing anything? It is just stuck doing nothing and I'm unable to do anything with this addon. 
I've even tried creating the sqlite file myself and no avail. It balloons to 116mb ?

Any help would be great! 

Steps/data to reproduce the behavior, e.g.
- (https://gtfs.adelaidemetro.com.au/v1/static/latest/google_transit.zip)
Issue with installing GTFS zip

**Release used**
Latest OS updates both HA and GTFS 0.4.5 - Raspi 4

**Additional**

**Comment by vingerha** [comment]
I cannot verify if you did the install right but it is on HACS since a few months now. When using the link above for a new stop it extracts fine in about 11 mins. I cannot check on its content

**Comment by Sheepish2** [comment]
What may cause the ballooning time? I’ll try reinstalling. 

Should I be downloading main? Or 0.4.5?

**Comment by Sheepish2** [comment]
Working fine now, took 3 days but retried and left over night 🤷🏽
