### ISSUE TITLE
Date time consistency

### ISSUE THREAD

**Issue by Pulpyyyy** [vingerha/gtfs2#7]
Departure/arival time are using full time format
![image](https://github.com/vingerha/gtfs2/assets/32004297/e67e03dd-785a-412d-9fc8-3d3bf5bda44d)
But others from GTFS datas are truncated
![image](https://github.com/vingerha/gtfs2/assets/32004297/32c44e24-f049-4490-92a1-c6b52b66fc56)
and requires the string extra+00:00 to be manipulated in HA
Others are even stranger, resembling an empty time zone
![image](https://github.com/vingerha/gtfs2/assets/32004297/47281ca0-22b7-4be7-a173-30e3b35e1761)

**Comment by vingerha** [comment]
This is HA 'platform' rules/conditions, State values can apply Timezone, Attributes not. I will check the devs

**Comment by vingerha** [comment]
All (!) attibiutes are now in UTC from dev release 1.6b3
