### ISSUE TITLE
refresh/update data

### ISSUE THREAD

**Issue by Pulpyyyy** [vingerha/gtfs2#8]
For example, here's a refresh problem: it's 9:34 p.m. and the next bus is still at 8:00 p.m.
![image](https://github.com/vingerha/gtfs2/assets/32004297/89b0b70a-5edf-4e9a-9587-5afdcfc85795)
and yet there was a following bus which is also overdue
![image](https://github.com/vingerha/gtfs2/assets/32004297/15487264-a927-40f9-8b4a-9a1502cc9ff1)

**Comment by vingerha** [comment]
The attributes show the last_update (so does the sensor)...is the sensor updated?
Errors in the log?

**Comment by vingerha** [comment]
Resolved in dev release 0.1.6c1
