### ISSUE TITLE
Unable to parse GTFS static data from Massachusetts Bay Transportation Authority

### ISSUE THREAD

**Issue by KautzA** [vingerha/gtfs2#84]
**Describe the bug**
MBTA GTFS static zip does not finish parsing after 4+ days. I could not find logs about a reason. Parsing the known-good https://baliabideak.bizkaia.eus/Bizkaibus/GTFS/Bizkaibus.zip (also by URL) from the wiki completed within 30 minutes. Is there an obvious reason why my local GTFS source does not parse / is the error one that GTFS2 could log visibly to the user?

**Steps/data to reproduce the behavior**
I followed steps 0 and 1 on the wiki using the following link for the MBTA dataset https://cdn.mbta.com/MBTA_GTFS.zip

LS -la shows the sqlite database is 192512 bytes which has not changed in days. The downloaded MBTA.zip is 8337410 bytes.
Searching the homeassistant logs for `gtfs` shows several entries such as the following with no other related messages.
`2024-05-28 17:36:20.143 WARNING (MainThread) [custom_components.gtfs2.gtfs_helper] Cannot use this datasource as still unpacking: MBTA`

**Release used**
- gtfs2 release 0.4.6.1
- HA type (HAOS running on raspberry pi 4)

**Additional**

MBTA static GTFS
https://mbta.com/developers/gtfs
https://cdn.mbta.com/MBTA_GTFS.zip

MBTA realtime GTFS
https://www.mbta.com/developers/gtfs-realtime
https://cdn.mbta.com/realtime/Alerts.pb
https://cdn.mbta.com/realtime/TripUpdates.pb
https://cdn.mbta.com/realtime/VehiclePositions.pb

**Comment by vingerha** [comment]
Have a look here: https://github.com/vingerha/gtfs2/issues/68
