### ISSUE TITLE
[FEATURE]: Add support for mobilitydatabase.org

### ISSUE THREAD

**Issue by stboch** [vingerha/gtfs2#85]
**Describe the solution you'd like**
I found https://mobilitydatabase.org/ in the process of reviewing my local transit authority. It could be a good source to pull and off up an eaiser interface for selection.

**Comment by vingerha** [comment]
I am not exactly sure why an integration with an external provider like this would be needed, most people use 1, maybe a few providers and these are fixed from there on. 
Second, the quality of such a provider is questionable, I have 4 providers and for this one:
- local bus, links to data of 5 months old, the newest I have is from yesterday
- local bus, links to data from 2022
- other country: data from 2021
- other country: not in the list
So already for me individually this is 0 value....people should not need to check the validity of the source but sadly this is required. My best sources are either the local transport-provider or gtfs.pro who are pretty stable in quality but I do also have issues during the year where all of a sudden the link stops working and need to find another one.

**Comment by vingerha** [comment]
Correction, I found the missing country and the data is up-to-date but... I have another source (gtfs.pro) that provides an optimised version  of 120Mb vs. 147Mb and this saves me about 1 hour of unpacking.... so I continue to see no value and I do need a proper incentive :)

**Comment by vingerha** [comment]
Closing as no further feedback
