### ISSUE TITLE
missing INDEX on database

### ISSUE THREAD

**Issue by FabienD74** [vingerha/gtfs2#88]
Hi,
I have  run the script found here ( https://github.com/pgexperts/pgx_scripts/blob/master/indexes/fk_no_index.sql  )

A) The report listed a few Missing indexes on "Foreign keys"

table stop_times : feed_id + stop_id
table trips: feed_id + service_id
table trips: feed_id + route_id

Those indexes should speed up navigation between tables

B) furthermore: 
Some indexes on dates in tables calendar and calendar_dates ?
Index on Latitude + Longitude on stops ?

I create all (A+ B)  on my side...
Searching departudes arround phone GPS : 300ms (down from 2-3 seconds) 

Should be tested on sqlite, but works fine on postgresql.

PS: Some indexes are already create at runtime.
Have a nice day

**Comment by vingerha** [comment]
On A:
table stop_times : feed_id + stop_id
table trips: feed_id + service_id
table trips: feed_id + route_id
In none of the sql that I use is the feed_id involved (as the db is always from 1 feed), so no sense to add that (yet)

On B:
None of the queries search for actual values in lat/lon, only boundaries in which the lat/lon falls, so a normal index makes no sense. Maybe a b-tree may help but this may add to the size too. I would also need to know the query times just to see if it adds substantially , i.e. I will not add anything if it goes from 1s to 0.9...that may be 10% but it has no effect on the end user perception

**Comment by vingerha** [comment]
can you pls copy the index create statements below?

**Comment by vingerha** [comment]
Removed the other message, the above lines, are these using the existing queries or queries already adapted for your personal case.
I would need both the index-create query as well as the query what you tested to see if this has any effect on SQLite...from what I recall, the first query with new indexes ran for 5s, the next ones below .0.5 and 2 but not sure

**Comment by vingerha** [comment]
Closing this as the proposed indexes do no apply to the current setup of gtfs2, neither are there complaints about performance. Not spending time to get this from already OK to more than OK
