### ISSUE TITLE
Issue with SNCF TER Real Time

### ISSUE THREAD

**Issue by tchup** [vingerha/gtfs2#90]
Hi,

**Describe the bug**
I did not succeed to add the source for SNCF trains Real time data (France).
The .zip file and the .sqlite file are created, but nothing happens.

![Capture d'écran 2024-06-13 222035](https://github.com/vingerha/gtfs2/assets/20298349/4ce053e0-45e9-43a9-8bfd-cfe4cdbe9e93)

Steps/data to reproduce the behavior:
- Adding datasource from URL: https://proxy.transport.data.gouv.fr/resource/sncf-ter-gtfs-rt-trip-updates

**Release used**
- gtfs2 0.4
- HA type : HAOS

**Additional**
Sorry, I don't know how to get the logs in HAOS.

Thanks for your help!

**Comment by vingerha** [comment]
The static data is not correct,, it should be many Mb in size. Remove those files and start again...please provide the source

**Comment by vingerha** [comment]
Examined this again, seems you used the realtime source to setup the static routes, that will never work. 
1. setup static data with the regular gtfs source
2. add realtime info, e.g. using above link
Closing this topic with above instruction

**Comment by tchup** [comment]
Sorry about that, I misunderstood the user guide and thought I had to add the realtime source directly.

Thanks for your work and the advice!

**Comment by tchup** [comment]
Unfortunately it still doesn't work. Realtime source seems to be added correctly, but no realtime update is gathered.

For exemple, trip id `OCESN871471F3308845:2024-06-19T00:38:12Z` is present and delayed in realtime data (see
[TER GTFS_converted.txt](https://github.com/user-attachments/files/15897765/TER.GTFS_converted.txt)).
But no realtime information is displayed by the sensor.

![RT](https://github.com/vingerha/gtfs2/assets/20298349/3f87bcb1-d6d1-4d08-bc18-561f70d4b791)


Sources are 
- static: https://eu.ftp.opendatasoft.com/sncf/gtfs/export-ter-gtfs-last.zip
- realtime: https://proxy.transport.data.gouv.fr/resource/sncf-ter-gtfs-rt-trip-updates

**Comment by vingerha** [comment]
As you may understand I cannot analyse this for each case/person so will need to ask for more input as qhat you provide is insufficient for me to even judge where it could be
You need to compare the stop_id in the entity with the stop_id in the RT file for the same trip_id, not just look at trip_id as sometimes (god knows why this is sometimes) TER leaves out stops in their trips (I have plenty of examples here in the 06)

**Comment by tchup** [comment]
No worry, I wasn't expecting a deep analysis but rather some guidance on where to look !
I will check further the stop IDs within the files. 

Merci encore !

**Comment by tchup** [comment]
The "stop_id" is correct, but the "direction_id" is 1 in the static data, 0 in the realtime data.
Can it be the cause of the issue ? If yes, is there an easy fix or should I contact the GTFS generator?

**Comment by vingerha** [comment]
So what you are saying is that the static stop shows the same trip_id as the on in teh RT and ths stop_id match too, that should (!) be sufficient.
I am not able to look at the code before end of the week but from what I recall it is a deviation from what I see as 'logic'

 It should not need the direction_id as this should (?) be part of the trip itself, i.e. a trip_id from A>B should be a different id when returning B>A but...well... I have been surprised too often.

**Comment by tchup** [comment]
Yes, trip_id and stop_id are consistent from what I saw.
In the example I checked, the trip was this one in the static data :

>  FR:Line::714D1126-C14B-45DD-8752-90285B45A41F:,002225,**OCESN854047F2479441:2024-06-19T00:38:12Z**,854047,1,26236,

and the stop this one : 

>**StopPoint:OCETrain TER-87334508**,La Poterie,,48.0923450,-1.6307730,,,0,StopArea:OCE87334508

The realtime data contained this : 
>   {
>         "id": "OCESN854047F2479441:2024-06-19T00:38:12Z",
>         "trip_update": {
>             "trip": {
>                 "trip_id": "**OCESN854047F2479441:2024-06-19T00:38:12Z**",
>                 "start_time": "14:15:00",
>                 "start_date": "20240619",
>                 "route_id": "",
>                 "direction_id": "0"
>             },
>             "stop_time_update": [
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87481648",
>                     "arrival": {
>                         "delay": 0,
>                         "time": 0
>                     },
>                     "departure": {
>                         "delay": 1500,
>                         "time": 1718800800
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87471367",
>                     "arrival": {
>                         "delay": 1800,
>                         "time": 1718802000
>                     },
>                     "departure": {
>                         "delay": 1800,
>                         "time": 1718802060
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87471359",
>                     "arrival": {
>                         "delay": 1800,
>                         "time": 1718802780
>                     },
>                     "departure": {
>                         "delay": 1800,
>                         "time": 1718802840
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87471342",
>                     "arrival": {
>                         "delay": 1800,
>                         "time": 1718803020
>                     },
>                     "departure": {
>                         "delay": 1800,
>                         "time": 1718803080
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87471334",
>                     "arrival": {
>                         "delay": 1800,
>                         "time": 1718803500
>                     },
>                     "departure": {
>                         "delay": 1800,
>                         "time": 1718803560
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87471326",
>                     "arrival": {
>                         "delay": 1800,
>                         "time": 1718803920
>                     },
>                     "departure": {
>                         "delay": 1800,
>                         "time": 1718803980
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87471318",
>                     "arrival": {
>                         "delay": 1800,
>                         "time": 1718804220
>                     },
>                     "departure": {
>                         "delay": 1800,
>                         "time": 1718804280
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87471029",
>                     "arrival": {
>                         "delay": 1800,
>                         "time": 1718804520
>                     },
>                     "departure": {
>                         "delay": 1800,
>                         "time": 1718804580
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "**StopPoint:OCETrain TER-87334508**",
>                     "arrival": {
>                         "delay": 1800,
>                         "time": 1718804880
>                     },
>                     "departure": {
>                         "delay": 1800,
>                         "time": 1718804940
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87471003",
>                     "arrival": {
>                         "delay": 1800,
>                         "time": 1718805300
>                     },
>                     "departure": {
>                         "delay": 0,
>                         "time": 0
>                     }
>                 }
>             ]
>         }
>     },

Thanks for looking at it, and obviously take your time, there is no hurry!

**Comment by vingerha** [comment]
Will look at it later, probably tomorrow or w/e. Do you know how overwrite the files in config/custom_components/gtfs2 ? I will provide something so that testing is faster, without a need to create releases (this is confusing for the others)

**Comment by vingerha** [comment]
I found the culprit. For route-based setup I am trying to extract multiple real-time values, if available. This only works when I use the route which can have mulitple trip_id which I am ignoring to get to 'all' rt-values. Now, your RT data does not have a router (yes...again a new situation) so it will not work as-is. Hereby a fix, could you please test this? 
[gtfs_rt_helper.zip](https://github.com/user-attachments/files/15912896/gtfs_rt_helper.zip)

**Comment by tchup** [comment]
I corrected line 197 to `if route_id = "": ` and it lanched without error. 
I'll run some testing and keep you updated.

**Comment by vingerha** [comment]
Sorry about that...I would love to say that I donot make this error often but sadly... I do :)

**Comment by tchup** [comment]
Still not working. :(

Trip : 
> FR:Line::6349C213-7B19-4078-BF2B-43CBECDA9545:,000065,OCESN886837F3331184:2024-06-20T00:38:09Z,886837,0,39662,

Stops:
> OCESN886837F3331184:2024-06-20T00:38:09Z,15:20:00,15:20:00,StopPoint:OCETrain TER-87726000,0,,0,1,
> OCESN886837F3331184:2024-06-20T00:38:09Z,15:29:00,15:30:00,StopPoint:OCETrain TER-87726307,1,,0,0,
> OCESN886837F3331184:2024-06-20T00:38:09Z,15:36:00,15:37:00,StopPoint:OCETrain TER-87726331,2,,0,0,
> OCESN886837F3331184:2024-06-20T00:38:09Z,15:47:00,15:48:00,StopPoint:OCETrain TER-87722405,3,,0,0,
> OCESN886837F3331184:2024-06-20T00:38:09Z,16:06:00,16:12:00,StopPoint:OCETrain TER-87723197,4,,0,0,
> OCESN886837F3331184:2024-06-20T00:38:09Z,16:17:00,16:18:00,StopPoint:OCETrain TER-87723502,5,,0,0,
> OCESN886837F3331184:2024-06-20T00:38:09Z,16:22:00,16:23:00,StopPoint:OCETrain TER-87723528,6,,0,0,
> OCESN886837F3331184:2024-06-20T00:38:09Z,16:25:00,16:26:00,StopPoint:OCETrain TER-87723536,7,,0,0,
> OCESN886837F3331184:2024-06-20T00:38:09Z,16:29:00,16:30:00,StopPoint:OCETrain TER-87723544,8,,0,0,
> OCESN886837F3331184:2024-06-20T00:38:09Z,16:33:00,16:34:00,StopPoint:OCETrain TER-87723569,9,,0,0,
> OCESN886837F3331184:2024-06-20T00:38:09Z,16:38:00,16:39:00,StopPoint:OCETrain TER-87723577,10,,0,0,
> OCESN886837F3331184:2024-06-20T00:38:09Z,16:45:00,16:46:00,StopPoint:OCETrain TER-87723585,11,,0,0,
> OCESN886837F3331184:2024-06-20T00:38:09Z,16:55:00,16:55:00,StopPoint:OCETrain TER-87743716,12,,1,0,


Realtime :
>     {
>         "id": "OCESN886837F3331184:2024-06-20T00:38:09Z",
>         "trip_update": {
>             "trip": {
>                 "trip_id": "OCESN886837F3331184:2024-06-20T00:38:09Z",
>                 "start_time": "15:20:00",
>                 "start_date": "20240620",
>                 "route_id": "",
>                 "direction_id": "0"
>             },
>             "stop_time_update": [
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87726000",
>                     "arrival": {
>                         "delay": 0,
>                         "time": 0
>                     },
>                     "departure": {
>                         "delay": 600,
>                         "time": 1718890200
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87726307",
>                     "arrival": {
>                         "delay": 300,
>                         "time": 1718890440
>                     },
>                     "departure": {
>                         "delay": 300,
>                         "time": 1718890500
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87726331",
>                     "arrival": {
>                         "delay": 300,
>                         "time": 1718890860
>                     },
>                     "departure": {
>                         "delay": 300,
>                         "time": 1718890920
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87722405",
>                     "arrival": {
>                         "delay": 300,
>                         "time": 1718891520
>                     },
>                     "departure": {
>                         "delay": 300,
>                         "time": 1718891580
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87723197",
>                     "arrival": {
>                         "delay": 300,
>                         "time": 1718892660
>                     },
>                     "departure": {
>                         "delay": 300,
>                         "time": 1718893020
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87723502",
>                     "arrival": {
>                         "delay": 600,
>                         "time": 1718893620
>                     },
>                     "departure": {
>                         "delay": 600,
>                         "time": 1718893680
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87723528",
>                     "arrival": {
>                         "delay": 600,
>                         "time": 1718893920
>                     },
>                     "departure": {
>                         "delay": 600,
>                         "time": 1718893980
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87723536",
>                     "arrival": {
>                         "delay": 600,
>                         "time": 1718894100
>                     },
>                     "departure": {
>                         "delay": 600,
>                         "time": 1718894160
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87723544",
>                     "arrival": {
>                         "delay": 600,
>                         "time": 1718894340
>                     },
>                     "departure": {
>                         "delay": 600,
>                         "time": 1718894400
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87723569",
>                     "arrival": {
>                         "delay": 600,
>                         "time": 1718894580
>                     },
>                     "departure": {
>                         "delay": 600,
>                         "time": 1718894640
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87723577",
>                     "arrival": {
>                         "delay": 600,
>                         "time": 1718894880
>                     },
>                     "departure": {
>                         "delay": 600,
>                         "time": 1718894940
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87723585",
>                     "arrival": {
>                         "delay": 600,
>                         "time": 1718895300
>                     },
>                     "departure": {
>                         "delay": 600,
>                         "time": 1718895360
>                     }
>                 },
>                 {
>                     "stop_sequence": 0,
>                     "stop_id": "StopPoint:OCETrain TER-87743716",
>                     "arrival": {
>                         "delay": 600,
>                         "time": 1718895900
>                     },
>                     "departure": {
>                         "delay": 0,
>                         "time": 0
>                     }
>                 }
>             ]
>         }
>     },

**Comment by vingerha** [comment]
Sigh, what did you setup ? La Pot > Chateau or vv?

**Comment by tchup** [comment]
No, each time  I change for a trip which is late,, because I don"t know if I will see something if it's on time.
This time it was `Meximieux - Pérouges` to `Ambérieu-en-Bugey`

**Comment by vingerha** [comment]
Please specify EXACTLY what you setup, add screenshots, I have no time to try and guess what it is

**Comment by vingerha** [comment]
Forget it, I am trying locally ... same issue...needs more time

**Comment by vingerha** [comment]
Almost there ... just a bit of context.... you may not be that interested but still :)
For regular bus/tram-routes I take a hard/unique stop_id and that allows to properly search the realtime data. 
For trains however, there is a different challenge as there can be multiple trains between two cities: short-stop, intercity, tgv, etc. and the main challenge is that they can depart/arrive on multiple platforms both at origin and destination. 
The platforms are the unique stop_id. 
If I would use the same method as for bus/tram then each individual stop_id (platform) needs to be specified and you would have to know the exact destination stop_id too. For a larger station with (say) 4 platforms and a destination with (say) 3 platforms, this leads to 12 combinations...which is unmanageable. 
Hence, for trains I use the 'city' which I based on a dataset having both buses, trams and trains
What I did no anticipate was a datasource TER which is only trains and still allows both city-city and stop-stop setup....missed this
Working on a solution but this requires a bit of redesign

**Comment by tchup** [comment]
Sorry for the confiusion about the settings! I'm changing constantly to have a delayed train set when I do the testing.

Thanks for looking into it!
I don't have the competency and time to modify myself the code, but I think these details can be useful if someone encounters some similar issues in the future with other sources.

**Comment by vingerha** [comment]
Try these 3 updates please
[upd.zip](https://github.com/user-attachments/files/15925417/upd.zip)

**Comment by tchup** [comment]
Yeah, it's working!!! Thank you!
![image](https://github.com/vingerha/gtfs2/assets/20298349/2413688d-8e56-45a4-a2cb-f05d6bec1ade)

**Comment by vingerha** [comment]
Thanks for the feedback, closing (hopefully now for good)

**Comment by tchup** [comment]
Just for information, SNCF TER alerts are using a truncated trip ID, for example
```
informed_entity {
    trip {
      trip_id: "OCESN864765F"
    }
```
instead of `OCESN864765F3273412:2024-06-27T00:35:30Z`

No need to reopen, because this is not the normal behavior (explained here: https://transport.data.gouv.fr/datasets/horaires-des-lignes-ter-sncf#dataset-discussions)

**Comment by vingerha** [comment]
The use of a timstamp in the RT trips was already a big surprise. I mean, how non-unique is this OCESN864765F3273412 ???
Why would you need a trip id related to a date/time in static data as well. But then truncating it even further ....sigh
There is way that I can relatively build a simple, global applicable solution here. 
BTW... the alerts that I am using is based on route so this would not work by default. I have only analysed 2 sources for alerts and neither of them had trip_id as identifier, so this one is a surprise too (gtfs is FULL of surprise)

**Comment by tchup** [comment]
Hi again,

After working well for several months, it appears that SNCF changed again the format. I don't have any data in my registered trips.

The trip ID now seems to include a date, as before, but not the date of the trip...
Example in realtime data for 05-05-2025 (same in static data)
```
{
        "id": "OCESN5516F3606169:2025-05-01T22:35:36Z",
        "trip_update": {
            "trip": {
                "trip_id": "OCESN5516F3606169:2025-05-01T22:35:36Z",
                "start_time": "08:50:00",
                "start_date": "20250505",
                "route_id": "",
                "direction_id": "0"
            },
            "stop_time_update": [
                {
                    "stop_sequence": 0,
                    "stop_id": "StopPoint:OCETGV INOUI-87755009",
                    "arrival": {
                        "delay": 0,
                        "time": 0
                    },
                    "departure": {
                        "delay": 0,
                        "time": 1746427800
                    }
             
```  

I guess this is again an unexpected behavior ?

**Comment by vingerha** [comment]
Closing it as it work
It took a while to find a route/trip that was actually present in the RT data, Cannes > Nice-Ville and this works. The format may be (way) odd but so is the static data, so TER is at least consistently odd :)

... and that is the main issue, TER hardly provides RT data.

**Comment by vingerha** [comment]
I have no clue, you should use the train setup and type in station names correctly

**Comment by tchup** [comment]
Sorry about that: it was not working because my source seemed to be stuck to an old version, even though I had tried to update it. 
I removed everything and reset it, it's working now, thanks !

**Comment by vingerha** [comment]
I found a possible issue, the route contains ':' and this may frustrate stop selection. Will create a fix-release in the next hour or so

**Comment by vingerha** [comment]
Even though it works, I will still continue to fix this odd thing too
