### ISSUE TITLE
Unable to add RealTime to my stop: error "expected str" when submitting config updates

### ISSUE THREAD

**Issue by CityDweller** [vingerha/gtfs2#92]
After adding my stop, I go to configure the stop to add RealTime.
enter the 3 URLs for TipUpdates, VehiclePosibion, and Alerts.
Everything else is default
Hit submit.

Page returns with "expected str"

I am on 2040.6.3 of HA and the latest GTFS2 via HACS.

stop information:
name: CATS
download URL: https://gtfsrealtime.ridetransit.org/GTFSStatic/api/GTFSDownload
/gtfs.zip
Route: 57
direction: outbound
from sotp 16 to stop 26
I named the stop "Home to work"

Once complete, click configure to add RT data; this is where I get the error.
<img width="962" alt="2024-06-16" src="https://github.com/vingerha/gtfs2/assets/2804911/337bbcbd-a798-4b1e-a9aa-e3441fcde8ca">

**Comment by vingerha** [comment]
Hi, I am aware of some oddities (that I myself introduced) ... can you type 'anything' in the api_key name?

**Comment by CityDweller** [comment]
I was able to add 'something' in the APIKey and it completed.
